services:
  - type: web
    name: mzd-kebap-website
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /